package com.solvd.talab.models;

import com.solvd.talab.common.ValidationsFunctions;
import com.solvd.talab.exceptions.InvalidCharacter;
import com.solvd.talab.exceptions.InvalidFormat;
import com.solvd.talab.exceptions.NegativeSpeedException;
import com.solvd.talab.interfaces.IVehicleMaintenance;
import com.solvd.talab.interfaces.IVehicleMovement;

import java.util.Locale;
import java.util.Objects;
import java.util.function.Function;

public abstract class Vehicle implements IVehicleMovement, IVehicleMaintenance {

    private String licensePlate;
    private float maxSpeed;
    private float kilometers;

    public float getMaxSpeed() {
        return maxSpeed;
    }

    public float getKilometers() {
        return kilometers;
    }

    //Final Attribute
    public final static int MAX_SPEED_ON_CITY = 60;

    public Vehicle(String licensePlate, float maxSpeed, float kilometers)throws NegativeSpeedException, InvalidCharacter  {
        this.kilometers = kilometers;
        //When we create a vehicle, license plate will be convert to uppercase
        licensePlate=formatLicensePlate(licensePlate, str -> str.toUpperCase());

        //Check if the speed is greater than 0 I throw NegativeSpeedException
        if (maxSpeed < 0)
            throw new NegativeSpeedException();
        else
            this.maxSpeed = maxSpeed;
        //Check if the license plate has invalid characters
        if (ValidationsFunctions.checkInvalidCharacter(licensePlate)) {
            try {
                //Check if the license plate has invalid format
                if (ValidationsFunctions.checkLicensePlateFormat(licensePlate))
                    this.licensePlate = licensePlate;
            } catch (InvalidFormat e) {
                e.getMessage();
            }
        }
    }

    public Vehicle(String licensePlate, float maxSpeed) throws NegativeSpeedException, InvalidCharacter {
        this.kilometers =0f;
        //When we create a vehicle, license plate will be convert to uppercase
        licensePlate=formatLicensePlate(licensePlate, str -> str.toUpperCase());

        //Check if the speed is greater than 0 I throw NegativeSpeedException
        if (maxSpeed < 0)
            throw new NegativeSpeedException();
        else
            this.maxSpeed = maxSpeed;
        //Check if the license plate has invalid characters
        if (ValidationsFunctions.checkInvalidCharacter(licensePlate)) {
            try {
                //Check if the license plate has invalid format
                if (ValidationsFunctions.checkLicensePlateFormat(licensePlate))
                    this.licensePlate = licensePlate;
            } catch (InvalidFormat e) {
                e.getMessage();
            }
        }

    }

    //Getters & Setters
    public String getLicensePlate() {
        return licensePlate;
    }

    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate;
    }



    @Override
    public String toString() {
        return
                "LicensePlate='" + licensePlate + '\'' +
                        ", speed=" + maxSpeed;
    }

    /*
    @Override
    public boolean equals(Object o) {
       if(o instanceof Vehicle){
           Vehicle other= (Vehicle) o;
           if(this.licensePlate == other.licensePlate)
               return true;
           else
               return false;
       }else
           return false;
    }*/

    //Autogenerated code
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Vehicle vehicle = (Vehicle) o;
        return licensePlate.equals(vehicle.licensePlate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(licensePlate);
    }


    @Override
    public void checkBrakes() {
        System.out.println("The mechanic checked the brakes");
    }

    //Task 3
    //Final method cannot be overridden
    public final void finalMethod() {
        System.out.println("This method cannot be overridden");
    }

    //Static method
    public static void staticMethod() {
        System.out.println("This is a static method");
    }

    //Task 8 Lambda functions
    private static String formatLicensePlate(String lp, Function<String,String> processor){
        return processor.apply(lp);
    }


}
